name: Deploy to App Tester
on:
  pull_request:
    branches:
      - 'main'
  push:
    tags:
      - 'ios*.*.*'

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.7'
          cache: true
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            # Caching build artifacts can be optional depending on your setup
            # build/ios/ipa/ci_cd.ipa
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - run: flutter pub get
      - run: flutter test
      - uses: cedvdb/action-flutter-build-ios@v1
        with:
          # always use --export-options-plist=ios/GithubActionsExportOptions.plist
          build-cmd: flutter build ipa --release --export-options-plist=ios/GithubActionsExportOptions.plist
          certificate-base64: ${{secrets.IOS_BUILD_CERTIFICATE_BASE64}}
          certificate-password: ${{secrets.IOS_BUILD_CERTIFICATE_PASSWORD}}
          provisioning-profile-base64: ${{secrets.IOS_MOBILE_PROVISIONING_PROFILE_BASE64}}
          keychain-password: ${{secrets.IOS_GITHUB_KEYCHAIN_PASSWORD}}
      - name: Archive IPA
        uses: actions/upload-artifact@v2
        with:
          name: release-ipa
          path: build/ios/ipa/ci_cd.ipa
      - run: ls build/ios/ipa/ci_cd.ipa
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: build/ios/ipa/ci_cd.ipa