name: Deploy to App Tester
on:
  pull_request:
    branches:
      - 'main'
  push:
    tags:
      - 'c*.*.*'
jobs:
  build-android :
    name: Upload ios to App Tester
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.7'
          cache: true
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            # Caching build artifacts can be optional depending on your setup
            # build/app/outputs/flutter-apk
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - run: flutter pub get
      - run: flutter test
      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          rubygems: latest
      - name: Fastlane Match setup
        run: |
          cd ios
          fastlane dev
      - name: flutter build iOS
        run: flutter build ios --release
          
    




          