name: Deploy to App Tester
on:
  pull_request:
    branches:
      - 'main'
  push:
    tags:
      - 'ios*.*.*'

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cedvdb/action-flutter-build-ios@v1
        with:
          # always use --export-options-plist=ios/GithubActionsExportOptions.plist
          build-cmd: flutter build ipa --release --export-options-plist=ios/GithubActionsExportOptions.plist
          certificate-base64: ${{secrets.IOS_BUILD_CERTIFICATE_BASE64}}
          certificate-password: ${{secrets.IOS_BUILD_CERTIFICATE_PASSWORD}}
          provisioning-profile-base64: ${{secrets.IOS_MOBILE_PROVISIONING_PROFILE_BASE64}}
          keychain-password: ${{secrets.IOS_GITHUB_KEYCHAIN_PASSWORD}}
      - name: Archive IPA
        uses: actions/upload-artifact@v2
        with:
          name: ci_cd.ipa
          path: build/ios/ipa/ci_cd.ipa
  distribute-ios:
    needs: build-ios
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ci_cd.ipa
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.CREDENTIAL_FILE_CONTENT}}
          groups: testers
          file: ci_cd.ipa