name: lint

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  lint:
    name: flutter analyze
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v3
      - name: set up java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.7'
          channel: 'stable'
          cache: true
      - name: flutter pub get
        run: flutter pub get
      - name: flutter analyze
        run: flutter analyze >> flutter_analyze_report.txt 2>&1
      - name: setup ruby
        if: ${{ failure() }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: setup danger
        if: ${{ failure() }}
        run: |
          gem install bundler
          bundle install
      - name: execute danger
        if: ${{ failure() }}
        uses: MeilCli/danger-action@v5
        with:
          plugins_file: "Gemfile"
          install_path: "vendor/bundle"
          danger_file: "Dangerfile"
          danger_id: "danger-pr"
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.TOKEN }}
      - name: Archive flutter_analyze_report
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: flutter_analyze_report
          path: /home/runner/work/ci_cd/ci_cd/flutter_analyze_report.txt
