name: Lint and Test Code

on:
  pull_request:
    branches:
      - 'main'
  push:
    tags:
      - 'lint*.*.*'
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.7'

      - name: Install dependencies
        run: flutter pub get

      - name: Run Flutter analyze
        run: flutter analyze

      - name: Check code formatting
        run: flutter format --set-exit-if-changed .

      - name: Run Flutter tests
        run: flutter test
